### ISSUE TITLE
Panic during validation in config.(*EncryptedTLSAssets).Compact (kube-aws v0.9.3-rc.2)

### ISSUE THREAD

**Issue by whereisaaron** [coreos/kube-aws#213]
Just making some new clusters with kube-aws 0.9.3-rc.2 and got this panic below. This was caused by running `kube-aws validate` in the wrong AWS account - so e.g. the encryption key was not available. It used the wrong account because I had set the `AWS_DEFAULT_PROFILE` environment variable, instead of `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`. So it was my error, but I assume the code is not supposed to panic in this situation.

```
$ kube-aws render stack
Success! Stack rendered to stack-template.json.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying stack-template.json or files in ./userdata.
3. Start the cluster with "kube-aws up".

$ kube-aws validate
Validating UserData...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x495ed8]

goroutine 1 [running]:
panic(0xa16260, 0xc420010090)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/coreos/kube-aws/config.(*EncryptedTLSAssets).Compact(0x0, 0xb, 0xc42012e5a0, 0xe)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/config/tls_config.go:375 +0xc8
github.com/coreos/kube-aws/config.ReadOrCreateCompactTLSAssets(0xafcaf0, 0xb, 0xc42012e5a0, 0xe, 0x0, 0x0, 0xc420019130, 0x50, 0xc42012e4e8, 0x7, ...)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/config/tls_config.go:437 +0x6a
github.com/coreos/kube-aws/config.Cluster.stackConfig(0xc4200b53e0, 0x15, 0xc42012e800, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc42012e4e8, 0x7, ...)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/config/config.go:626 +0x186
github.com/coreos/kube-aws/config.Cluster.ValidateUserData(0xc4200b53e0, 0x15, 0xc42012e800, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc42012e4e8, 0x7, ...)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/config/config.go:644 +0x77
github.com/coreos/kube-aws/cmd.runCmdValidate(0xee96a0, 0xf0acc0, 0x0, 0x0, 0x0, 0x0)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/cmd/validate.go:50 +0x19d
github.com/coreos/kube-aws/vendor/github.com/spf13/cobra.(*Command).execute(0xee96a0, 0xf0acc0, 0x0, 0x0, 0xee96a0, 0xf0acc0)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/vendor/github.com/spf13/cobra/command.go:632 +0x23e
github.com/coreos/kube-aws/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xee8e20, 0x0, 0x0, 0x0)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/coreos/kube-aws/vendor/github.com/spf13/cobra.(*Command).Execute(0xee8e20, 0xc42012bf50, 0xc4200001a0)
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/Users/cw_kuoka/Gopath/src/github.com/coreos/kube-aws/main.go:9 +0x2d
```

**Comment by redbaron** [comment]
fixed in master

**Comment by whereisaaron** [comment]
This is a duplicate of #202 _"Unclear error message when AWS credentials are missing in validate"_ sorry. Thanks for confirming resolved.
