### ISSUE TITLE
calico-node.service and calico-policy-controller are failing to start

### ISSUE THREAD

**Issue by mumoshu** [coreos/kube-aws#37]
I have been running a kube-aws E2E test against a cluster created from https://github.com/coreos/kube-aws/pull/34 (with [minor fixes basically unrelated to how etcd+calico works](https://github.com/coreos/kube-aws/compare/v0.9.0...mumoshu:stabilize-kubelet-startup)) and seeing the error like:

from `journalctl -e -u calico-node.service`:

```
Nov 06 06:56:24 ip-10-0-0-80.ap-northeast-1.compute.internal systemd[1]: Started Calico per-host agent.
Nov 06 06:56:24 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]: image: using image from file /usr/lib64/rkt/stage1-images/stage1-fly.aci
Nov 06 06:56:25 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]: image: using image from local store for image name quay.io/calico/node:v0.19.0
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]: Traceback (most recent call last):
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]:   File "startup.py", line 292, in <module>
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]:     client = IPAMClient()
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]:   File "/usr/lib/python2.7/site-packages/pycalico/datastore.py", line 228, in __init__
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]:     "%s" % (ETCD_CA_CERT_FILE_ENV, etcd_ca))
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]: pycalico.datastore_errors.DataStoreError: Invalid ETCD_CA_CERT_FILE. Certificate Authority cert is required and must be
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal rkt[25660]: Calico node failed to start
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal systemd[1]: calico-node.service: Main process exited, code=exited, status=1/FAILURE
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal systemd[1]: calico-node.service: Unit entered failed state.
Nov 06 06:56:29 ip-10-0-0-80.ap-northeast-1.compute.internal systemd[1]: calico-node.service: Failed with result 'exit-code'.
Nov 06 06:56:30 ip-10-0-0-80.ap-northeast-1.compute.internal systemd[1]: calico-node.service: Service hold-off time over, scheduling restart
```

from `kubectl get po --all-namespaces`:

```
$ kubectl get po --all-namespaces
NAMESPACE       NAME                                                                     READY     STATUS              RESTARTS   AGE
calico-system   calico-policy-controller-ip-10-0-0-102.ap-northeast-1.compute.internal   1/2       CrashLoopBackOff    6          10m
calico-system   calico-policy-controller-ip-10-0-0-103.ap-northeast-1.compute.internal   1/2       CrashLoopBackOff    5          9m
kube-system     heapster-v1.2.0-3646253287-hp1cm                                         0/2       ContainerCreating   0          11m
kube-system     kube-apiserver-ip-10-0-0-102.ap-northeast-1.compute.internal             1/1       Running             0          10m
kube-system     kube-apiserver-ip-10-0-0-103.ap-northeast-1.compute.internal             1/1       Running             0          8m
kube-system     kube-controller-manager-ip-10-0-0-102.ap-northeast-1.compute.internal    1/1       Running             0          9m
kube-system     kube-controller-manager-ip-10-0-0-103.ap-northeast-1.compute.internal    1/1       Running             0          8m
kube-system     kube-dns-v20-qdkp8                                                       0/3       ContainerCreating   0          11m
kube-system     kube-proxy-ip-10-0-0-102.ap-northeast-1.compute.internal                 1/1       Running             0          10m
kube-system     kube-proxy-ip-10-0-0-103.ap-northeast-1.compute.internal                 1/1       Running             0          8m
kube-system     kube-proxy-ip-10-0-0-58.ap-northeast-1.compute.internal                  1/1       Running             0          9m
kube-system     kube-proxy-ip-10-0-0-59.ap-northeast-1.compute.internal                  1/1       Running             0          10m
kube-system     kube-proxy-ip-10-0-0-60.ap-northeast-1.compute.internal                  1/1       Running             0          10m
kube-system     kube-proxy-ip-10-0-0-61.ap-northeast-1.compute.internal                  1/1       Running             0          10m
kube-system     kube-scheduler-ip-10-0-0-102.ap-northeast-1.compute.internal             1/1       Running             0          9m
kube-system     kube-scheduler-ip-10-0-0-103.ap-northeast-1.compute.internal             1/1       Running             0          8m
```

I'm not sure whether it is caused by the changes from the PR or not right now.

**Comment by mumoshu** [comment]
According to the error message from `journalctl -e -u calico-node.service` and my e2e result, this seems to be resolved once @camilb's `calico-ssl` branch (https://github.com/coreos/kube-aws/pull/33) is merged 😄 

```
Ran 105 of 385 Specs in 2724.677 seconds
SUCCESS! -- 105 Passed | 0 Failed | 0 Pending | 280 Skipped PASS
```

**Comment by mumoshu** [comment]
@camilb Long story short, I'm going to merge your branch referred in the PR #33 into not only the `experimental/external-etcd` branch but also `master`.

It turns out to me that we have been already breaking the calico integration since the discrete etcd branch was merged, which seems to force etcd clients like calico-node.service's to talk to etcd in TLS thus the error message?

(Please note that "breaking the calico integration" here means that once we've provided `useCalico: true` in `cluster.yaml`, clusters created with `kube-aws` won't fully function i.e. calico-policy-controller falls into crash loop, kube-dns won't come up, etc.)

So I'm going to merge your branch into not only the `experimental/external-etcd` branch but also `master`.

cc'ing @pieterlange (if you had already seen those calico related things, I'd greatly appreciate your confirmation 🙏 )
cc'ing @colhom (sry i've missed something but I'd been believing that this isn't mentioned in your original PR to coreos-kubernetes. I'd greatly appreciate it if I could have your confirmation 🙏 )

**Comment by pieterlange** [comment]
@mumoshu yes i've seen the calico PR and i can confirm `useCalico: true` was broken - didn't create an issue because i didn't have time to investigate but it indeed looked like a systemd crashloop because calico couldn't talk to etcd. Will try the new calico setup soon! thanks @camilb!

**Comment by camilb** [comment]
@mumoshu Fixed the ETCD certificates path in #39 when using calico.

**Comment by mumoshu** [comment]
@camilb Thanks for the fix!

Btw, it looks to me that it is functionally equivalent before/after your fix.
Maybe your fix is intended to make the naming of the volume mounted to `calico-node.service` match with the ones mounted to existing ones like `kubelet.service`, `flanneld.service`, etc.

Am I correct? (I'll merge your fix once it is confirmed 👍)

**Comment by camilb** [comment]
@mumoshu Also changed the volumes names, but the location of ETCD certificates in env cause failure when calico is enabled. Didn't test with calico disabled, but when it's enabled the cluster never comes up.

**Comment by mumoshu** [comment]
@camilb Excuse me if I'm missing something, but it seems to me that I've successfully created a calico-enabled cluster without #42. Nothing seems to be failing so far:

```
$ kubectl get po --all-namespaces
NAMESPACE       NAME                                                                    READY     STATUS    RESTARTS   AGE
calico-system   calico-policy-controller-ip-10-0-0-98.ap-northeast-1.compute.internal   2/2       Running   0          37m
calico-system   calico-policy-controller-ip-10-0-0-99.ap-northeast-1.compute.internal   2/2       Running   0          37m
kube-system     heapster-v1.2.0-4088228293-x4fkt                                        2/2       Running   0          37m
kube-system     kube-apiserver-ip-10-0-0-98.ap-northeast-1.compute.internal             1/1       Running   0          36m
kube-system     kube-apiserver-ip-10-0-0-99.ap-northeast-1.compute.internal             1/1       Running   0          36m
kube-system     kube-controller-manager-ip-10-0-0-98.ap-northeast-1.compute.internal    1/1       Running   0          36m
kube-system     kube-controller-manager-ip-10-0-0-99.ap-northeast-1.compute.internal    1/1       Running   1          37m
kube-system     kube-dns-v20-v9nwy                                                      3/3       Running   0          37m
kube-system     kube-proxy-ip-10-0-0-253.ap-northeast-1.compute.internal                1/1       Running   0          36m
kube-system     kube-proxy-ip-10-0-0-254.ap-northeast-1.compute.internal                1/1       Running   0          37m
kube-system     kube-proxy-ip-10-0-0-4.ap-northeast-1.compute.internal                  1/1       Running   0          36m
kube-system     kube-proxy-ip-10-0-0-6.ap-northeast-1.compute.internal                  1/1       Running   0          36m
kube-system     kube-proxy-ip-10-0-0-98.ap-northeast-1.compute.internal                 1/1       Running   0          36m
kube-system     kube-proxy-ip-10-0-0-99.ap-northeast-1.compute.internal                 1/1       Running   0          36m
kube-system     kube-scheduler-ip-10-0-0-98.ap-northeast-1.compute.internal             1/1       Running   0          37m
kube-system     kube-scheduler-ip-10-0-0-99.ap-northeast-1.compute.internal             1/1       Running   0          36m
kube-system     kubernetes-dashboard-v1.4.1-l0pdp                                       1/1       Running   0          37m
```

If necessary, you can try/replicate my setup with cloning #45

**Comment by camilb** [comment]
@mumoshu Looks strange since envs like `Environment=ETCD_CERT_FILE=/etc/etcd2/ssl/etcd-client.pem`are pointing nowhere.  Maybe there is something I'm missing. I will let you know as soon as I finish the tests.

**Comment by mumoshu** [comment]
@camilb Good to see it works! Thanks for your help :bow:
